# Generated by Django 4.1.2 on 2025-01-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('check_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
