# Generated by Django 5.1.5 on 2025-03-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('upload_date', models.DateField()),
            ],
        ),
    ]
