# Generated by Django 5.1.5 on 2025-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='obj_metadata',
            field=models.JSONField(default={'a': 1}),
            preserve_default=False,
        ),
    ]
