# Generated by Django 5.1.5 on 2025-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0003_userdata_obj_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='obj_metadata',
            field=models.JSONField(null=True),
        ),
    ]
