# Name of the workflow
name: Application tests
# Running workflow on pull request
on:
  pull_request:
    branches:
      - main

jobs:
  # Name of the job
  test-app:
    runs-on: ubuntu-latest
    # Storing all the secrets in environment
    env:
      db_name: ${{ secrets.DATABASE_NAME }}
      db_user: ${{ secrets.DATABASE_USER }}
      db_password: ${{ secrets.DATABASE_PASSWORD }}
      db_host: ${{ secrets.DATABASE_Host }}
      db_port: ${{ secrets.DATABASE_PORT }}
      django_secret: ${{ secrets.SECRET_KEY }}
      debug: ${{ secrets.DEBUG }}
      default_db_user: ${{ secrets.DEFAULT_DB_USER }}
      default_db_password: ${{ secrets.DEFAULT_DB_PASSWORD }}

    steps:
      # Cloning repository to the github workspace
      - name: Check out repository code
        uses: actions/checkout@v4
      # Updating package list
      - name: Update the package list
        run: sudo apt-get update
      # Installing python
      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      # Installing Mysql server
      - name: Installing mysql server
        run: sudo apt-get install mysql-server -y
      # Setting up mysql server database
      - name: Setting up database
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "create database $"db_name";" -u$default_db_user -p$default_db_password
          mysql -e "create user '$"db_user"'@'$"db_host"' identified by '$"db_password"';" -u$default_db_user -p$default_db_password
          mysql -e "grant all privileges on $"db_name".* to '$"db_user"'@'$"db_host"';" -u$default_db_user -p$default_db_password
          mysql -e "grant all privileges on test_$"db_name".* to '$"db_user"'@'$"db_host"';" -u$default_db_user -p$default_db_password
      # Adding application user and group
      - name: Adding user and group
        run: |
          sudo groupadd $"db_user"
          sudo useradd -g $"db_user" $"db_user"
      # Installing remaining dependencies that are required
      - name: Installing dependencies
        run: |
          sudo apt-get install python3-venv -y
          sudo apt-get install pkg-config python3-dev default-libmysqlclient-dev build-essential -y
      # Creating virtual environment for application to run and install packages
      - name: Creating virtual environment and installing required packages
        run: |
          sudo python3 -m venv appenv
          source appenv/bin/activate
          pip install -r requirements.txt
      # Changing ownership and permission of the folder to the application user 
      - name: Changing ownership of app to be able to run by application user
        run: |
          sudo chown -R $"db_user":$"db_user" .
          sudo chmod -R 755 .
      # Creating .env file which is required by the application
      - name: Creating environment file for application
        run: |
          sudo runuser webapp -c "cat > .env << EOF
          DEBUG=$"debug"
          SECRET_KEY=$"django_secret"
          DATABASE_NAME=$"db_name"
          DATABASE_USER=$"db_user"
          DATABASE_PASSWORD=$"db_password"
          DATABASE_Host=$"db_host"
          DATABASE_PORT=$"db_port"
          EOF"
      # Running application tests
      - name: Testing app
        run: |
          sudo -u $"db_user" bash -c "source appenv/bin/activate && python3 manage.py makemigrations"
          sudo -u $"db_user" bash -c "source appenv/bin/activate && python3 manage.py migrate"
          sudo -u $"db_user" bash -c "source appenv/bin/activate && python3 manage.py test"