# Name of the workflow
name: Application tests
# Running workflow on pull request
on:
  pull_request:
    branches:
      - main

jobs:
  # Name of the job
  test-app:
    runs-on: ubuntu-latest
    # Storing all the secrets in environment
    env:
      db_name: ${{ secrets.DATABASE_NAME }}
      db_user: ${{ secrets.DATABASE_USER }}
      db_password: ${{ secrets.DATABASE_PASSWORD }}
      db_host: ${{ secrets.DATABASE_Host }}
      db_port: ${{ secrets.DATABASE_PORT }}
      django_secret: ${{ secrets.SECRET_KEY }}
      debug: ${{ secrets.DEBUG }}
      default_db_user: ${{ secrets.DEFAULT_DB_USER }}
      default_db_password: ${{ secrets.DEFAULT_DB_PASSWORD }}

    steps:
      # Cloning repository to the github workspace
      - name: Check out repository code
        uses: actions/checkout@v4
      # Updating package list
      - name: Update the package list and upgrade packages
        run: |
         sudo apt-get update
         sudo apt-get upgrade -y
      # Installing python
      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      # Setting up mysql server database as it is by default installed on ubuntu machines provided by github
      # and also creating users for database and granting permission to that user
      - name: Setting up database and creating database users and providing
        run: |
          sudo systemctl start mysql.service
          mysql -u $default_db_user -p$default_db_password -e"create database $db_name;"
          mysql -u $default_db_user -p$default_db_password -e"create user '$db_user'@'$db_host' identified by '$db_password';"
          mysql -u $default_db_user -p$default_db_password -e"grant all privileges on $db_name.* to '$db_user'@'$db_host';"
          mysql -u $default_db_user -p$default_db_password -e"grant all privileges on test_$db_name.* to '$db_user'@'$db_host';"
      # Installing remaining dependencies that are required
      - name: Installing dependencies
        run: |
          sudo apt-get install python3-venv -y
          sudo apt-get install pkg-config python3-dev default-libmysqlclient-dev build-essential -y
      # Creating virtual environment for application to run and install packages
      - name: Installing required packages by python
        run: pip install -r requirements.txt
      # Creating .env file which is required by the application
      - name: Creating environment file for application
        run: |
          sudo cat > .env << EOF
          DEBUG=$debug
          SECRET_KEY=$django_secret
          DATABASE_NAME=$db_name
          DATABASE_USER=$db_user
          DATABASE_PASSWORD=$db_password
          DATABASE_Host=$db_host
          DATABASE_PORT=$db_port
          EOF
      # Running application tests
      - name: Testing app
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py test